version: "3.9"

services:
  cristianredin:
    image: ghcr.io/CristianRedin/devopsssss:1.0.0

    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"

        # HTTP → HTTPS
        - "traefik.http.routers.cristianredin.entrypoints=http"
        - "traefik.http.routers.cristianredin.rule=Host(`cristianredin.byronrm.com`)"
        - "traefik.http.middlewares.cristianredin-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.cristianredin.middlewares=cristianredin-https-redirect"

        # HTTPS
        - "traefik.http.routers.cristianredin-secure.entrypoints=https"
        - "traefik.http.routers.cristianredin-secure.rule=Host(`cristianredin.byronrm.com`)"
        - "traefik.http.routers.cristianredin-secure.tls=true"
        - "traefik.http.routers.cristianredin-secure.tls.certresolver=letsencrypt"
        - "traefik.http.routers.cristianredin-secure.service=cristianredin"

        # Puerto interno del contenedor
        - "traefik.http.services.cristianredin.loadbalancer.server.port=3000"

        # Red pública de traefik
        - "traefik.docker.network=traefik-public"

    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
